openapi: 3.0.0
info:
  title: OpenWeatherMap API
  description: This API provides weather information for cities around the world.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/AEXCEL780/openweatherapi/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://api.openweathermap.org/data/2.5
  description: OpenWeatherMap API server
paths:
  /weather:
    get:
      summary: Get weather by city name
      parameters:
      - name: q
        in: query
        description: The name of the city
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: London
      - name: appid
        in: query
        description: Your API key
        required: true
        style: form
        explode: true
        schema:
          type: string
            example: Your_API_KEY
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Unauthorized. Invalid API key.
        "404":
          description: City not found
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        main:
          type: object
          properties:
            temp:
              type: number
              description: Temperature in Kelvin
            humidity:
              type: integer
              description: Humidity percentage
